### ISSUE TITLE
watch jobs on all tenants

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#112]
current watch api only works on specific tenant

the saas quota system (to be GAed soon) need watch backup jobs and restore jobs for all tenants.

ks will ensure this api can only be issued by admin.

**Comment by shaofeng66** [comment]
endpoints:
/jibuapis/ys.jibudata.com/v1alpha1/backupjobs?watch=true
/jibuapis/ys.jibudata.com/v1alpha1/restorejobs?watch=true

**Comment by stoneshi-yunify** [comment]
@shaofeng66 thanks, can you add the new watch api in backup-saas-client?

**Comment by shaofeng66** [comment]
Yes, I am adding these 2 watch api in saas backend then will update go client.

**Comment by shaofeng66** [comment]
@stoneshi-yunify Please see 
https://github.com/jibutech/backup-saas-client/blob/main/samples/backupjob_test.go#L250
https://github.com/jibutech/backup-saas-client/blob/main/samples/restorejob_test.go#L175

for code to watch jobs in all tenants by passing an empty string("") as tenant to WatchBackupJobs/WatchRestoreJobs

**Comment by stoneshi-yunify** [comment]
fixed, thanks
