### ISSUE TITLE
failed to create restoreplan with same namespace on another cluster

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#12]
![image](https://user-images.githubusercontent.com/70880165/133879374-08d8bd43-5645-4df6-b3f6-388b467a0ccb.png)

I backed up the `test` namespace on cluster A, and I want to restore it to the same namespace `test` on cluster B. When creating the restoreplan, it threw above error.

test namespace does not exist on cluster B, so I think it should allow it.

**Comment by jerry-jibu** [comment]
fix is done by loosing namespace mapping
