### ISSUE TITLE
get latest job for a plan

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#14]
ks needs to show the latest job's status for a plan, but there is no way to easily get it. 

can jibu provide a new api to show such extensive information? 

e.g.

get the latest N jobs for a plan `..../[backup|restore]plan/xxx?extensive=true&limits=N`
return both the plan and job objects, e.g.
```
// plan status
status:
    latestjobs:
    - job-1
    - job-2
    - ...
```

**Comment by jerry-jibu** [comment]
under fixing.

**Comment by jerry-jibu** [comment]
`lastBackupJobName` & `lastBackupJobPhase` will be added to backup CR to simplify UI display.

**Comment by shaofeng66** [comment]
fixed by adding CurrentJobName and CurrentJobPhase on backupplan CR.

**Comment by stoneshi-yunify** [comment]
can we also do this to restoreplan?

**Comment by shaofeng66** [comment]
yes, I will add this.
