### ISSUE TITLE
currentJobName and currentJobPhase is not correct

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#23]
**Describe the bug**
1.When I delete the currentJob of a backup plan ,the `currentJobName` and `CurrentJobPhase` dose not exist. In fact , there are other jobs.
2.When the status of a currentJob changes to JobCompleted, the currentJobPhase of the plan remains JobInProgress.

**Expected behavior**
 `currentJobName` and `currentJobPhase` are always the latest jobs for the plan

picture for the bug 1:
![image](https://user-images.githubusercontent.com/63338728/137106741-a08a8753-8411-4825-9bff-c35f459bbdde.png)

picture for the bug 2:
![image](https://user-images.githubusercontent.com/63338728/137106693-81067e37-21a1-411c-9678-f8c7328b5bbc.png)

**Comment by shaofeng66** [comment]
for bug2, it is due to a code bug that ignoring the update conflict of CR.
for bug1, I will fix it by always set CurrentJobName and CurrentJobPhase to latest job.
