### ISSUE TITLE
Lack of admin to view all cluster/storage/backupPlan/restorePlan  apis

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#25]
For better maintenance, we need to view all of clusters, storages, backupPlans and restorePlans in the admin background, but now, we don't have an Admin API

**Comment by shaofeng66** [comment]
will use URLs:
/jibuapis/ys.jibudata.com/v1alpha1/clusters
/jibuapis/ys.jibudata.com/v1alpha1/storages
/jibuapis/ys.jibudata.com/v1alpha1/restoreplans
/jibuapis/ys.jibudata.com/v1alpha1/restoreplans
