### ISSUE TITLE
 Restoring resources from the v1.21 K8S cluster  to the V1.20 K8S cluster fails

### ISSUE THREAD

**Issue by liuyp2018** [jibutech/backup-saas-client#38]
**Test environment:**
Source cluster1:
K8s version: v1.21.5
Single cluster environment

Target cluster2:
K8s version: v1.20.6
Multi-cluster environment

Root cause: Restore from 1.21 to 1.20, EndpointSlice versions are inconsistent

**Comment by jerry-jibu** [comment]
The fix is through enabling velero  `--feature=enableAPIGroupVersions`, regression test is completed.

**Comment by liuyp2018** [comment]
verified and fixed
