### ISSUE TITLE
update CustomResourceDefinition version to v1

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#4]
```
root@master1:~/go/src/github.com/jibutech/backup-saas-client
$ ./deploy.sh
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition <=====
customresourcedefinition.apiextensions.k8s.io/backupjobs.migration.yinhestor.com created
```

k8s v1.22 has been released on Aug, and I think we won't support k8s < 1.16. So we need to update to v1 asap otherwise jibu backup won't work on k8s 1.22+.

**Comment by jerry-jibu** [comment]
These CRD will be only deployed in our environment. 
With velero 1.6.3, it can detect user's environment, such as 1.22 to install velero v1 and v1beta1 on <= 1.15.

**Comment by jerry-jibu** [comment]
I think we could defer this to next release ? v1beta1 -> v1 is also on our software release roadmap.

**Comment by stoneshi-yunify** [comment]
ks will release v3.2 this month maybe and it will support k8s v1.22. that means, if jibu doesn't support 1.22, and user is using ks v3.2 with k8s 1.22, he will not be able to use the jibu backup service.

**Comment by stoneshi-yunify** [comment]
> ks will release v3.2 this month maybe and it will support k8s v1.22. that means, if jibu doesn't support 1.22, and user is using ks v3.2 with k8s 1.22, he will not be able to use the jibu backup service.

sorry, seems i'm misunderstanding something. just to check if any crds with apiextensions.k8s.io/v1beta1 could be deployed on user's cluster, not jibu's backend cluster.

**Comment by jerry-jibu** [comment]
let's support v1.22 in phase 2 or phase 3.

**Comment by stoneshi-yunify** [comment]
velero already supports apiextensions.k8s.io/v1 and jibu does not deploy any other crds in user's cluster, so we're fine.

jibu's backend client can not deploy on k8s v1.22, that's okay as end user will not be aware of jibu client.
