### ISSUE TITLE
Query parameters and sorting problems

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#40]
According to KS.cloud's design,  it is necessary to support the query function and sorting by some specific fields
![image](https://user-images.githubusercontent.com/63338728/140672602-0e48e31d-b9ad-492b-bcf1-e537c035d631.png)

**Comment by shaofeng66** [comment]
支持的字段可以参考 [文档](https://github.com/jibutech/backup-saas-for-kubesphere-cloud/blob/main/user_guide/%E5%A4%87%E4%BB%BD%E5%AE%B9%E7%81%BESAAS%E5%BC%80%E5%8F%91%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3.md)，其中按时间过滤的时间范围用“<from>~<to>”指定，日期的格式为RFC3339且时区需要是GMT时间，比如
```curl -XGET 'http://127.0.0.1:31800/jibuapis/ys.jibudata.com/v1alpha1/tenants/go-client-test/backupplans?spec.backupPlanRef.namespaces=wordpress&spec.backupPlanRef.clusterName=k8s&status.report.endTime=2021-11-04T08:17:35Z~2021-11-04T08:17:48Z'```

**Comment by fuchunlan** [comment]
> 支持的字段可以参考 [文档](https://github.com/jibutech/backup-saas-for-kubesphere-cloud/blob/main/user_guide/%E5%A4%87%E4%BB%BD%E5%AE%B9%E7%81%BESAAS%E5%BC%80%E5%8F%91%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3.md)，其中按时间过滤的时间范围用`“<from>~<to>”`指定，日期的格式为RFC3339且时区需要是GMT时间，比如 `curl -XGET 'http://127.0.0.1:31800/jibuapis/ys.jibudata.com/v1alpha1/tenants/go-client-test/backupplans?spec.backupPlanRef.namespaces=wordpress&spec.backupPlanRef.clusterName=k8s&status.report.endTime=2021-11-04T08:17:35Z~2021-11-04T08:17:48Z'`

ok, thanks
