### ISSUE TITLE
delete jibu object returns ok but get/list object still shows it

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#47]
案例：用户在console中删除了一个备份计划，刷新页面，发现计划还在。

原因是骥步调用了k8sclient进行资源的删除，k8sclient把资源标记为删除（设置metadata.deletiontimestamp）就马上返回200了。这时候get/list资源还能看到。

建议：
- 骥步的deletexxx api，调用k8sclient删除object后，应get object确认此object是否还存在，如果存在，返回非200？
- list/get 不返回删除中的资源？
- 骥步应清理（force delete)长期存在的删除中的资源

**Comment by stoneshi-yunify** [comment]
per discussion, jibu will:
- add a query parameter for the deletiontimestamp for list method, like `WithDeleting`, default value `false`, so by default list will not get these objects.
- periodically check and clean up any objects stuck in deleting

**Comment by shaofeng66** [comment]
Added a common filter "deletionTimestamp". 
If this filter is not specified, all objects that marked as deleted( DeletionTimestamp is not empty) are filtered out. 
If this filter is specified, it works like a normal time range filter, e.g. 2021-11-15T22:02:02Z~2021-11-16T22:26:02Z

**Comment by stoneshi-yunify** [comment]
verified fixed by new client
