### ISSUE TITLE
list methods does not support paginator and query parameters

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#5]
as the title

**Comment by jerry-jibu** [comment]
How about support pagination like Kubernetes way: https://kubernetes.io/docs/reference/using-api/api-concepts/
`GET /api/v1/pods?limit=500` & `GET /api/v1/pods?limit=500&continue=ENCODED_CONTINUE_TOKEN`  ?

**Comment by stoneshi-yunify** [comment]
@fuchunlan see if the k8s native paginator meets ks-fronend's need.  the code can be found here https://github.com/jibutech/backup-saas-for-kubesphere-cloud/blob/aa6fbe49f7a1b5387b5669dd58a75ab5480a97c8/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L411


> How about support pagination like Kubernetes way: https://kubernetes.io/docs/reference/using-api/api-concepts/
> `GET /api/v1/pods?limit=500` & `GET /api/v1/pods?limit=500&continue=ENCODED_CONTINUE_TOKEN` ?

**Comment by stoneshi-yunify** [comment]
I think the k8s native way might be suitable as it's not a real `paginator`. It doesn't even have a `page` or `total pages` count. 

btw, here is the paginator struct ks is using, see if you can reuse it.


```golang
type Filter struct {
	Key      string      `json:"key"`
	Value    interface{} `json:"value"`
	Operator Operator    `json:"operator"`
}

type Paginator struct {
	TotalPages uint   `json:"total_pages"`
	TotalCount uint64 `json:"total_count"`
	Page       uint   `json:"page"`
	PerPage    uint   `json:"per_page"`
}

type Query struct {
	Filter []Filter `json:"filter"`
	// default is ASC, if the key starts with `-`, means DESC
	OrderBy   []string  `json:"order_by"`
	Paginator Paginator `json:"paginator"`
}

```

The Query struct will be read from http request. And the result object will have the `Paginator` too.
e.g.
```golang
func (u *ClusterUsecase) List(ctx context.Context, query domain.Query) (domain.ClusterList, domain.Error) {
}

type ClusterList struct {
	Paginator Paginator  `json:"paginator"`
	Clusters  []*Cluster `json:"clusters"`
}
```
