### ISSUE TITLE
need advanced combined query

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#54]
Front-end code restrictions, it is not convenient to query front-end processing，so need for advanced combination of queries
The main scene：
【backup plans】
![image-20211122112230469](https://user-images.githubusercontent.com/63338728/142801908-a936637e-670f-4196-aa09-931348d10515.png)

【restore plans】
![image-20211122112331422](https://user-images.githubusercontent.com/63338728/142801918-831e45d6-d85e-40dd-a48f-48ca112b940e.png)

【backup jobs】
![image-20211122112412381](https://user-images.githubusercontent.com/63338728/142801895-3d473450-3d6d-4e93-91a8-a578b2e77913.png)

**Comment by stoneshi-yunify** [comment]
经过和骥步讨论，长期来看，骥步后端支持此查询比较好，前端查询单个条件最后再merge可能无法达到预期的效果（比如merge后如何分页和sort？），可能需要增加domain language or middleware.

当前决定的fix是修改前端设计，每个查询条件/field作为下拉框里的一个选项，用户一次只能选择一个field进行查询。

**Comment by stoneshi-yunify** [comment]
ks is aware of the restriction and will work around.

@fuchunlan  please close this issue, thanks.
