### ISSUE TITLE
almost every backup plan takes 4+ minutes to be ready

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#61]
clouddev env

almost every backup plan takes 4+ minutes to be ready, this is extremely slow. check more info on clouddev with: kubectl -n backup-tenant-369641743475338021 get backupplans.ys.jibudata.com

**Comment by jerry-jibu** [comment]
Thanks @27149chen to help investigate this performance issue. 

Background is that after adding a remote cluster and have more than 40 backup plans,  mig-controller would become very slowly to reconcile any new backup plan.

**Comment by jerry-jibu** [comment]
Also add stone's test script: https://github.com/stoneshi-yunify/jibutest

**Comment by stoneshi-yunify** [comment]
the backup plan becomes ready very fast now
