### ISSUE TITLE
failfast for restore job

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#65]
AFAIK, the following restore situations will definitely fail:
-  the dest cluster does not have the storageclass from backup
- the backup has NodePort service, and the dest cluster already occupied this nodeport by other services/applications

If we could check the stroageclass/nodeport on the dest cluster before restore, the success rate will be improved.

**Comment by stoneshi-yunify** [comment]
looks like the case 1 `storageclass missing` is already covered by current jibu client:
```
  - category: Warn
    lastTransitionTime: "2021-12-03T13:58:42Z"
    message: PV in `persistentVolumes` [pvc-4dbe210c-9aaa-43a2-b28e-d35b6f08c51c]
      has no expected storageclasses. Make sure that the necessary storageclasses
      exist in the destination cluster.
    reason: NotFound
    status: "True"
    type: PvNoStorageClassSelection
```

**Comment by stoneshi-yunify** [comment]
when some essential conditions are not met, the restore job should fail fast instead of pending of keeping inprogress.

**Comment by jerry-jibu** [comment]
let's use error not a warning for this case.

**Comment by stoneshi-yunify** [comment]
fixed
