### ISSUE TITLE
pause scheduled backup plan

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#81]
need jibu to support this feature so that a plan won't generate job automatically anymore

**Comment by jerry-jibu** [comment]
`pause` flag for repeated backup plan is under implementation.

**Comment by shaofeng66** [comment]
fixed in saas release 20211222

set spec.policy.pause to true to pause a repeat plan.

**Comment by stoneshi-yunify** [comment]
verified fixed
