### ISSUE TITLE
plan already exists

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#89]
If create a backup plan with the same name immediately after deleting a backup plan, an error "xxx already exists" is reported.
![image](https://user-images.githubusercontent.com/63338728/148507629-d0ccf9cf-d551-4063-9473-b02671f23dff.png)

**Comment by stoneshi-yunify** [comment]
look at the origError `object is being deleted ...`, the object is marked to be deleted, but it will present for a while (normally a few seconds) before really disappear.

Suggest ks frontend uses the filter `deletionTimestamp` to check if a backup plan name exists. refer : https://github.com/jibutech/backup-saas-client/issues/47#issuecomment-970326540
