### ISSUE TITLE
backup plans were set to error phase after cluster shutdown then restart

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#92]
![image](https://user-images.githubusercontent.com/70880165/149742302-5740dc8d-8efe-4987-9b6d-1dc94d82c370.png)

![image](https://user-images.githubusercontent.com/70880165/149742336-a349d348-372c-4e77-834e-8a9f8b44bee4.png)

- 用户的集群欠费停机后充值恢复，之后登陆ks.cloud，发现之前ready的备份计划现在都是error状态

**Comment by 27149chen** [comment]
fixed in https://github.com/jibudata/mig-controller/pull/75
